### PR TITLE
Remove patch which invalidates the serial chip at extr

### PR DESCRIPTION
**Pull request by ekoeppen**
Update TMainPlatformDriver to keep the serial chip at hardware location
extr around and remove the corresponding patch. The chip at extr will be
handled by Einstein's serial port emulation.

Update the REx binary.

### CODE REVIEW

**Comment by MatthiasWM** [comment]
I assume my serial port emulation will no longer work when applying this PR.
Do you have plans to update serial emulation to use your new driver system, or would that be my job?

**Comment by ekoeppen** [comment]
> I assume my serial port emulation will no longer work when applying this PR.

The idea is to keep it working, since the ROM patch which changes `extr` to `~xtr` should not be needed when not registering a fake serial chip in TMainPlatformDriver, i.e. leave the driver in place so that the DMA based implementation will be used. 

Registering the fake chip in TMainPlatformDriver and then removing it with a patch is a bit redundant :)

> Do you have plans to update serial emulation to use your new driver system, or would that be my job?

I'm working on that, making steady progress (there are some implications when the Voyager serial subsystem is not in use at all).

**Comment by ekoeppen** [comment]
I'll merge this now after checking again that the existing port emulation is still in use. It's anyway an easy change to revert :)

**Comment by MatthiasWM** [comment]
Thanks for checking. I remember that back when I wrote this ten plus years ago, that a driver was loaded, that blocked things (it wouldn't do anything, and not call any of the original routines either), so I patched it away. Now with the Rex compilable agin and a functioning driver in the Rex, we have a completely different approach. But that was such a long Tim ago.

**Pull request merged**
