### PR TITLE
Windows command line build.

### PR DESCRIPTION
**Pull request by MatthiasWM**
This is a complete and tested build setup for MS Windows.

It's by far easier to build Einstein from the command line than describing every button click in the VisualStudio user interface. This setup will also build FLTK and Newt64 without the need to install either. The instructions will build in Release mode for Intel 64bit processors.

### CODE REVIEW

**Comment by pguyot** [comment]
Do you think we could add Windows to the CI? GitHub supports [Windows 2019 and Windows 2022](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on).

**Comment by MatthiasWM** [comment]
Yes, that will work. It's one of the reasons for this test. I also looked into Continuous Distribution as well, so we can easily release new version for all platforms and publish them here on GitHub. The exact same order of commands should build the Linux and MacOS version as well, including your tests. Testing it right now.

**Comment by MatthiasWM** [comment]
Current settings are too strict for my Ubuntu version and I get errors for not using the return value from ::write() etc. . But the basic principle works very well ;-)

**Comment by pguyot** [comment]
Excellent. We could also look at generating some code coverage report and then start testing things beyond pure ARM emulation as the application includes more features now such as networking or the toolkit. The initial tests were manually run and some have not been automated.

**Comment by MatthiasWM** [comment]
I don't know much about testing processes, but I'll be happy to learn.

**Comment by MatthiasWM** [comment]
Yay, CI works!

**Pull request merged**
