### PR TITLE
linux resurrection

### PR DESCRIPTION
**Pull request by hfmanson**
Added several files from google code SVN version which are needed.
Maybe they should be substituted by more recent files.
At least the following files are missing:

Newt/CLibrary/newt_string.cp
Newt/Common/Globals.cp
Newt/Common/Glue.cp
Newt/Frames/Objects.cp
Newt/Frames/TInterpreter.cp
Newt/UtilityClasses/CArrayIterator.cp
Newt/UtilityClasses/CDynamicArray.cp
Emulator/JIT/TJIT.cp

### CODE REVIEW

**Comment by MatthiasWM** [comment]
All the Newt/ stuff is not needed to compile and run Einstein. Only if it is compiled and linked into the executable, it will patch itself into the emulator at run-time. This is all highly experimental, so for Linux, simply leave it out.

**Comment by MatthiasWM** [comment]
Closing....

**Comment by hfmanson** [comment]
Hello Matthias,

I threw out Newt stuff out of _Build_/Jam/Jamfile. Now Emulator/JIT/TJIT.cp
is still missing, what should happen with this file?

**Comment by MatthiasWM** [comment]
> On Feb 16, 2015, at 5:50 PM, hfmanson <notifications@github.com> wrote:
> 
> Hello Matthias,
> 
> I threw out Newt stuff out of _Build_/Jam/Jamfile. Now Emulator/JIT/TJIT.cp
> is still missing, what should happen with this file?
> 

That directory should only contain:

JIT.h
TJITCache.h and .cp
TJIT.h
TJITPage.h and .cp
TJITPerformance.h and .cp

I assume yoou can delete that reference as well

**Comment by hfmanson** [comment]
Hello Matthias,

The new pull request I just created successfully compiles einstein, but no
X11 window is created just now. See comment in pull request

Regards,
Henri

**Pull request closed without merging**
