### PR TITLE
Add different serial port schemes

### PR DESCRIPTION
**Pull request by ekoeppen**

### CODE REVIEW

**Comment by MatthiasWM** [comment]
I see that you add stuff on the driver side. Does this mean that you are creating a "real" driver and we can eventually remove the emulation on the west hardware level?

**Comment by ekoeppen** [comment]
Yes, something along those lines :) The Voyager serial support is a bit tricky to adjust to a generic host driver (as noted in the Einstein code already, a lot of intercepting of register accesses), so while keeping that, I added a generic serial driver layer. I’m reconstructing at the moment what I had working last year prior to the big merge. I used this to interface with an external Bluetooth chip via a stripped down Bluetooth stack (https://github.com/ekoeppen/btstack-newton <https://github.com/ekoeppen/btstack-newton>).

Eckhart

**Comment by MatthiasWM** [comment]
Wow! Sorry for stomping on stuff with that merge. I wasn't aware that you were still developing. I should make sure that alll dev efforts are more in sync ;-)

**Comment by ekoeppen** [comment]
No worries! I was more or less pausing before the merge because I saw that you’re working on putting the code lines back together. The pause was a bit longer than planned, but I’m happy that the merge went through, and the code I was working on was anyway not impacted.

Eckhart

**Comment by MatthiasWM** [comment]
There is one big change for you though which you probably found already. ```.../app/TFLRexImage.fl``` integrates ```../_Data_/Einstein.rex``` into the binaries of Einstein, so it needs no longe be there. Fluid - the FLTK User Interface Designer, can't tell CMake about dependencies, so if you change the ```Einstein.rex```, also touch ```TFLRexImage.fl```, so that CMake creates the ```TFLRexImage.cpp``` again.

**Pull request merged**
