### PR TITLE
Installer for essential apps.

### PR DESCRIPTION
**Pull request by MatthiasWM**
This feature adds a menu item in the help menu that
opens a dialog box, listing some of the essential
programs that many users want to patch the y2k10 issue,
to go online, or to read eMail.

### CODE REVIEW

**Comment by MatthiasWM** [comment]
https://github.com/pguyot/Einstein/blob/c270bbf4ccd1a82b600086b6c3cc9ab7140b99ec/app/TFLSettingsUI.fl#L1213

@panicsteve @pguyot @ekoeppen @turbolent @jake-b @chuma @MatthiasWM  

Hi guys. I added Licenses and Contributors text to the Einstein About dialog (see link above). I added everyone who was listed on GitHub adding over 1000 lines, and I wrote a little synopsis. Before I want to make this public in a few weeks, I would like your input:

Did I forget anyone? Did I write too little, too much about you? Do you not want to be mentioned? As always, all comments are welcome!
Screenshot 2022-01-03 at 23 37 45

**Comment by panicsteve** [comment]
Someone other than me did the initial port to iOS!  (I thought it was you, Matthias! :D)  But I've been helping where I can to keep those builds working for the last several versions of macOS, iOS, and Xcode.  At some point (when it was built on Jam), I updated the Jamfiles to make it build on the then-current Ubuntu, and roughly on a Raspberry Pi.  :) 

My contribution to the Monitor was hacking the CLI version to work somewhat in the Mac GUI version.  I don't think I actually added anything to the core Monitor functionality.

A few typos I noticed:

- "Contributore to Einstein" -> "Contributors to Einstein"
- "At WWNC 2006, he release" -> "At WWNC 2006, he released"
- "JIT translateion" -> "JIT translation"
- "newer C cmopiler" -> "newer C compiler"
- "Victore keeps" -> "Victor keeps"
- "who privided ideas" -> "who provided ideas"

**Comment by splorp** [comment]
One more tweak to the contributor text … **Jake-B** should be fully attributed as **Jake Bordens**.

**Comment by MatthiasWM** [comment]
Thanks. I fixed the typos and modified Steves role after re-learning that I actually did the original iOS port many eons ago.

"<h4><a href=\"https://github.com/MatthiasWM\">Matthias Melcher</a></li></h4>\n"
"Matthias ported Einstein to the MSWindows, and later to iOS and Android.\n"
"He has since added a full user interface on all platforms\n"
"and unified the build process for macOS, Windows, and Linux under the user interface\n"
"library FLTK. He added serial port and PCCard emulation and a minimal integrated developer environment.\n"
"He started a port to Android that is still stuck in Beta, hoping for volunteers.\n"

"<h4><a href=\"https://github.com/panicsteve\">Steven Frank</a></li></h4>\n"
"Steven updated Einstein for iOS and for native macOS,\n"
"and he improved the debugging Monitor on macOS.\n"

**Comment by MatthiasWM** [comment]
Oh, minus the last Android mention in my block.

**Comment by MatthiasWM** [comment]
PR moved to #124

**Pull request closed without merging**
