### PR TITLE
Linux fixes

### PR DESCRIPTION
**Pull request by chuma**
Redoing pull request #36.  Now I know not to touch `Drivers/`.

* New PulseAudio sound driver - tested on Linux Fedora 27.  I am getting smooth sound.
* Some improvements (I think) to PortAudio sound output, though it's still not perfect.
* Option to use system PortAudio library instead of the included sources - YMMV.
* `_Build_/Jam/Jamfile`
  * translated to English
  * cleaned up to work on my Fedora linux machine.  
  * added options to specify which sound outputs to build.
* K libraries may now be built with CMake, though the Einstein Jamfile build doesn't pick up where the library ends up (yet).
* `K/_Build_/Jam/Jamfile` also got some Linux love.

### CODE REVIEW

**Comment by MatthiasWM** [comment]
Trying to get this compiled on Fedora, but the Fedora installer `dnf` does not allow i386 dependencies (or at least not a way that I saw). Sigh. On macOS, there is no harm in compiling Einstein in 64 bit. I wonder if that is true for Linux as well.

**Comment by chuma** [comment]
`dnf install libfoo.i686`

Fedora 32-bit packages are i686, not i386

**Comment by chuma** [comment]
Making 64-bit build on Linux will be one of the next things I try as well.

**Comment by MatthiasWM** [comment]
OK, thanks for the hint. I did get it to compile very nicely and to run even better. I get 20'000 iterations running the emulator in Linux inside Parallels VM on MacOS. Blazingly fast! Thanks!!!

**Pull request merged**
