### PR TITLE
Cleaning up CMake file

### PR DESCRIPTION
**Pull request by MatthiasWM**
I am restructuring the CMake system big time. To the outside it should look and behave exactly as before, but I am fixing a few maintenance worries. I would like your OKs on this since this may have issues when merging other Pull Requests. Thanks.

Problem: the top-level CMakeLists.txt has become huge and unmaintainable
* I started to generate CMakeLists in the subdirectories, taking the load off the top level
* I use newer CMake options when I find them
* I remove code duplication between platforms whenever I find them

Problem: the `app` directory has become very crowded
* I moved all FLTK build related files into a subdirectory named `FLTK`
* Adjusted CMake files

Is that OK for you guys?

### CODE REVIEW

**Comment by ekoeppen** [comment]
Thanks for the heads up, sounds like a good idea!

**Comment by pguyot** [comment]
I do have a local WIP branch fixing #115 by using [gtest](https://github.com/google/googletest) on Linux. This work also revealed unnecessary dependencies between subdirectories. It will conflict with this as I did edit the root CMakeLists.txt. Should we merge it first?

**Comment by MatthiasWM** [comment]
Phew, so I was able to rebase my stuff onto Paul's latest commit. I left out my new root `CMakeLists.txt` because the changes are too extreme to just merge like that. If CI works, I will merge this and add my other changes later piece-by-piece so that I don't destroy any new CMake features by Paul.

**Comment by MatthiasWM** [comment]
@pguyot `K` and some other parts still had CMakeLists.txt file in subdirectories. I assume they have been stale for years as they still refer to `.cp` instead of `.cpp` file endings. In retrospect, I did back then step on the ability to compile K and Emulator as independent libraries. 

This system builds a monolithic Einstein, but separating libraries should not be too difficult if you ever want to go back to that system.

**Comment by MatthiasWM** [comment]
So I decided to push my changes. The main CMakeFile.txt that was recently reorganised by Paul to add tests stays pretty much unchanged. My CMake changes are therefore not active yet. 

I did however move the FLTK stuff out of the crowded `app` folder.

I will try to merge my CMake changes with Paul's in a different PR.

**Comment by pguyot** [comment]
The CI was broken with this PR.
Could we please only merge PRs that do not break it? It seems to be a but in CodeQL, which is suspicious since this PR was about moving files and editing CMakeLists.

**Comment by MatthiasWM** [comment]
> The CI was broken with this PR.
> Could we please only merge PRs that do not break it? It seems to be a bug in CodeQL, which is suspicious since this PR was about moving files and editing CMakeLists.

Yes, my bad. I was impatient. I am trying to fix everything in #138.

CodeQL seems to have run out of memory, and that may have been my fault: Xcode needs a dependency of Einstein on EinsteinTests because they are using the same input files (I don't know why either). Also, one of the main complaints by CodeQL related to FLTK/Fluid was finally fixed.

Thanks for installing CodeQL. It's a double incentive for me in improving Fluid *and* Einstein at the same time. And to write better code.

**Comment by pguyot** [comment]
Apparently, CI has been fixed indeed with #138
Thanks!
https://github.com/pguyot/Einstein/runs/4790008287?check_suite_focus=true

I only ran a couple of tests to see which sets of rules broke (it was with the full set and this very commit).

**Comment by MatthiasWM** [comment]
LGTM's opinion ist still out. There are a lot of infos and warnings for Fluid generated code which I won't be able to fix. I'll make a list when I know the details and then we can see what a good strategy will be.

**Comment by MatthiasWM** [comment]
OK< so there are two patterns that create warnings in CodeQL. Fluid generates this code:
```
Fl_Group *o = new Fl_Group().. {
  { Fl_Button *o = new Fl_Button() { ... }
  }
  { Fl_Button *o = myNamedButton = new Fl_Button() { ... }
  }
}
```
Warning 1 will complain that `myNamedButton` is not deleted in the destructor. Well, FLTK deletes all children when deleting the parent group, so deleting `myNamedButton` after deleting the group would cause a crash. FLTK apps rely on that behaviour.

The other issue is a note that `Fl_Button *o` will hide `Fl_Group *o`. That is true, but one convention for Fluid requires that the name `o` is available in user-written callback. So no way to change that either.

I don't really want to remove generated `.cpp` files entirely, because they do contain user-written code as well. Do you have an idea how to solve this? Can we set markers in the source code to suspend CodeQL for a number of lines?

**Comment by pguyot** [comment]
Unfortunately, we cannot disable tests by line or file. We can disable queries on LGTM, which is great as some obviously generate false positives or design decisions that are aguably correct (for example including files that are not header files, or listing constants that are not used). For CodeQL CI, we can chose a smaller set of test and enable queries we find interesting. Or we can be very careful when new errors occurs and live with the current set of 500+ alerts.

**Pull request merged**
